config/routes.rb
Rails.application.routes.draw do
  get 'download/show'

	resources :products  
	get 'home/index'
	get 'home/index2'
	get 'home/index3'
	# get '/download' => 'products#download'
	root 'products#index'
	devise_for :users
	resources :home
	resources :pdf
	resources :download
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	def self.to_csv(options = {})
		desired_columns = ["id", "name", "released_on", "price"]
		CSV.generate(options) do |csv|
			csv << desired_columns
			all.each do |product|
				csv << product.attributes.values_at(*desired_columns)
			end
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
	# geocoded_by :full_street_address   # can also be an IP address
 #    after_validation :geocode          # auto-fetch coordinates
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base	
	protect_from_forgery with: :exception
	# before_action :require_online, only: [:show]
	# private
	# def require_online
	# redirect_to root_path unless @product == ture 
	# end
end

app/controllers/download_controller.rb
class DownloadController < ApplicationController
	before_action :authenticate_user!, only: [:show]
	def show
		@product = Product.find(params[:id])
		respond_to do |format|
			format.html
			format.csv { send_data product.to_csv }
			format.xls 
			format.pdf do
				render pdf: "index.pdf.erb"
			end
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	#before_action :authenticate_user!, only: [:show]
	def index
	end
	def index2
	end
	def index3
	end
	def show
		@product = Product.find(params[:id])
		respond_to do |format|
			format.html
			format.csv { send_data product.to_csv }
			format.xls 
			format.pdf do
				render pdf: "index.pdf.erb"
			end
		end
	end
end

app/controllers/pdf_controller.rb
class PdfController < ApplicationController
	def show
		@product = Product.find(params[:id])
		respond_to do |format|
			format.html
			format.csv { send_data product.to_csv }
			format.xls 
			format.pdf do
				render pdf: "index.pdf.erb"
			end
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, only: [:show, :edit, :update, :destroy]
	respond_to :html, :xml, :js, :pdf
	 # before_action :authenticate_user!, only: [:show]
	 def index
	 	@products = Product.all
	 end
	 def show
	 	respond_to do |format|
	 		format.html
	 		format.csv { send_data product.to_csv }
	 		format.xls 
	 		format.pdf do
	 			render :pdf => "show.pdf",
	 			:disposition => "inline",
	 			:template => "products/show.pdf.erb",
	 			:layout => "application.html"
	 		end 
	 	end
	 end

	 def new
	 	@product = Product.new
	 end

	 def edit
	 end


	 def create
	 	@product = Product.new(product_params)

	 	respond_to do |format|
	 		if @product.save
	 			format.html { redirect_to @product, notice: 'Product was successfully created.' }
	 			format.json { render :show, status: :created, location: @product }
	 		else
	 			format.html { render :new }
	 			format.json { render json: @product.errors, status: :unprocessable_entity }
	 		end
	 	end
	 end


	 def update
	 	respond_to do |format|
	 		if @product.update(product_params)
	 			format.html { redirect_to @product, notice: 'Product was successfully updated.' }
	 			format.json { render :show, status: :ok, location: @product }
	 		else
	 			format.html { render :edit }
	 			format.json { render json: @product.errors, status: :unprocessable_entity }
	 		end
	 	end
	 end

	 def destroy
	 	@product.destroy
	 	respond_to do |format|
	 		format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
	 		format.json { head :no_content }
	 	end
	 end

	 private
	 def set_product
	 	@product = Product.find(params[:id])
	 end

	 def product_params
	 	params.require(:product).permit(:name, :released_on, :price, :special)
	 end
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pdf_helper.rb
module PdfHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/download/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.try(:name) %>
</p>

<p>
  <strong>Released on:</strong>
  <%= @product.try(:released_on) %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.try(:price) %>
</p>

app/views/home/index.html.erb
<script  src="http://maps.google.com/maps/api/js?sensor=false">
</script>
<b><p id="demo"></p></b>
<script>
   var x = document.getElementById("demo");
   if (navigator.geolocation){
    navigator.geolocation.getCurrentPosition(showCurrentLocation);
}
else{
   alert("Geolocation API not supported.");
}

function showCurrentLocation(position){
    var address = position.coords.address;
    var latitude = position.coords.latitude;
    var longitude = position.coords.longitude;
    var coords = new google.maps.LatLng(latitude, longitude, address);
    x.innerHTML="Latitude: " + position.coords.latitude + 
    "<br>Longitude: " + position.coords.longitude + 
    "<br>address: " + position.coords.address;
    // alert('Your latitude is :'+latitude+' and longitude is '+longitude);

    var mapOptions = {
        zoom: 15,
        center: coords,
        mapTypeControl: true,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    };

            //create the map, and place it in the HTML map div
            map = new google.maps.Map(
                document.getElementById("mapPlaceholder"), mapOptions
                );

            //place the initial marker
            var marker = new google.maps.Marker({
                position: coords,
                map: map,
                title: "Current location!"
            });
        }
    </script>
    <div>
        <h2>HTML5 Show Location on GoogleMap Sample</h2>
        <div id="mapPlaceholder"></div>
    </div>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB_A6R-m635-RxYIiErJkl08dLbVL5dtUA
    &callback=initMap"
    async defer></script>
<script  src="https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522,151.1957362&radius=500&type=restaurant&keyword=cruise&key=AIzaSyC1vcTN9FVRd9LOi3JeQ6zfnD5m2DPNv3M
"></script>
<script src="https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photoreference=CnRtAAAATLZNl354RwP_9UKbQ_5Psy40texXePv4oAlgP4qNEkdIrkyse7rPXYGd9D_Uj1rVsQdWT4oRz4QrYAJNpFX7rzqqMlZw2h2E2y5IKMUZ7ouD_SlcHxYq1yL4KbKUv3qtWgTK0A6QbGh87GB3sscrHRIQiG2RrmU_jF4tENr9wGS_YxoUSSDrYjWmrNfeEHSGSc3FyhNLlBU&key=AIzaSyCKiS6__xIAM-6HIBoOF10sb5D4Frq7FMs"></script>
    

app/views/home/index2.html.erb
<div class="row">
  <div class="col-md-2 col-sm-2 col-xs-2">
    <p>
      <button class="btn btn-primary btn-sm" id="get-location-btn"><span>Get Location</span>
      </button></p>
    </div><!-- .col -->
    <div class="col-md-10 col-sm-10 col-xs-10">
      <div class="panel panel-default">
        <div class="panel-heading">Location Response</div>
        <div class="panel-body">
          <p>Lat/Long: <input id="location-lat-long" type="text" class="form-control"/></p>
          <p>Address: <input id="location-address" type="text" class="form-control"/</p>
          <p>Map:</p><div id="map-container" style="height: 400px;"></div>
        </div>
      </div>
    </div><!-- .col -->
  </div><!-- .row -->

  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
  <script>
    "use strict";
    
    $(document).ready(function() {

    // get location button functionality
    $("#get-location-btn").click(function(event){
      event.preventDefault();
      $("#location-lat-long").val("Finding location. Please wait...");
      // check if browser supports the geolocation api
      if(navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(success);      // if geolocation supported, call function
      } else {
        $("#location-lat-long").val('Your browser doesn\'t support the geolocation api.');
      }
      
    });
    
    // function to get lat/long and plot on a google map
    function success(position) {
      var latitude    = position.coords.latitude;       // set latitude variable
      var longitude   = position.coords.longitude;      // set longitude variable
      
      var mapcanvas   = document.createElement('div');    // create div to hold map
      mapcanvas.id = 'map';                   // give this div an id of 'map'
      mapcanvas.style.height = '400px';             // set map height
      mapcanvas.style.width = '100%';               // set map width
      
      document.querySelector('#map-container').appendChild(mapcanvas);  // place new div within the 'map-container' div
      
      var coords = new google.maps.LatLng(latitude,longitude);  // set lat/long object for new map

      var options = {                       // set options for map
        zoom: 15,
        center: coords,
        mapTypeControl: false,
        navigationControlOptions: {
          style: google.maps.NavigationControlStyle.SMALL
        },
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };

      var map = new google.maps.Map(document.getElementById("map"), options); // create new map using settings above
      var marker = new google.maps.Marker({           // place a marker at our lat/long
        position: coords,
        map:    map
      });
      
      var latLongResponse = 'Latitude: ' + latitude + ' / Longitude: ' + longitude; // build string containing lat/long
      getAddress(latitude,longitude);             // geocode the lat/long into an address
      $("#location-lat-long").val(latLongResponse);                 // write lat/long string to input field
      
    }


    // function to process address data
    function processAddress(address) {
      $("#location-address").val(address);                  // write address to field
      var spokenResponse = "I've got you at " + address;            // build string to speak
      speakText(spokenResponse);                        // speak the address
    }

    // function to geocode a lat/long
    function getAddress(myLatitude,myLongitude) {

      var geocoder  = new google.maps.Geocoder();             // create a geocoder object
      var location  = new google.maps.LatLng(myLatitude, myLongitude);    // turn coordinates into an object
      
      geocoder.geocode({'latLng': location}, function (results, status) {
        if(status == google.maps.GeocoderStatus.OK) {           // if geocode success
          processAddress(results[0].formatted_address);         // if address found, pass to processing function
        } else {
          alert("Geocode failure: " + status);                // alert any other error(s)
          return false;
        }
      });
    }


    // function to speak a response
    function speakText(response) {

      // setup synthesis
      var msg = new SpeechSynthesisUtterance();
      var voices = window.speechSynthesis.getVoices();
      msg.voice = voices[2];          // Note: some voices don't support altering params
      msg.voiceURI = 'native';
      msg.volume = 1;             // 0 to 1
      msg.rate = 1;             // 0.1 to 10
      msg.pitch = 2;              // 0 to 2
      msg.text = response;
      msg.lang = 'en-US';
      
      speechSynthesis.speak(msg);
    }
  });
</script>
<!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyABu-LRKepyEl5q3Js4MsP_RTIehpQloxA&callback=initMap" 
 async defer></script> -->

app/views/home/index3.html.erb
<!DOCTYPE html>

<html>

<head>
 <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
 <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>
</head>

<body>
  <p>Address: <div id="address"></div></p>
<!--   <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAFxuBAepYTKrU8fIIamVPllrBAmKEvg1w&callback=initMap"
  async defer></script> -->
</body>

<script type="text/javascript" charset="utf-8">

 $(document).ready(function() {
   var currgeocoder;

         //Set geo location lat and long

         navigator.geolocation.getCurrentPosition(function(position, html5Error) {

           geo_loc = processGeolocationResult(position);
           currLatLong = geo_loc.split(",");
           initializeCurrent(currLatLong[0], currLatLong[1]);

         });

        //Get geo location result

        function processGeolocationResult(position) {
             html5Lat = position.coords.latitude; //Get latitude
             html5Lon = position.coords.longitude; //Get longitude
             html5TimeStamp = position.timestamp; //Get timestamp
             html5Accuracy = position.coords.accuracy; //Get accuracy in meters
             return (html5Lat).toFixed(8) + ", " + (html5Lon).toFixed(8);
           }

        //Check value is present or not & call google api function

        function initializeCurrent(latcurr, longcurr) {
         currgeocoder = new google.maps.Geocoder();
         console.log(latcurr + "-- ######## --" + longcurr);

         if (latcurr != '' && longcurr != '') {
           var myLatlng = new google.maps.LatLng(latcurr, longcurr);
           return getCurrentAddress(myLatlng);
         }
       }

        //Get current address

        function getCurrentAddress(location) {
          currgeocoder.geocode({
            'location': location

          }, function(results, status) {
           
            if (status == google.maps.GeocoderStatus.OK) {
              console.log(results[0]);
              $("#address").html(results[0].formatted_address);
            } else {
              alert('Geocode was not successful for the following reason: ' + status);
            }
          });
        }
      });

    </script>

    </html>

app/views/home/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.try(:name) %>
</p>

<p>
  <strong>Released on:</strong>
  <%= @product.try(:released_on) %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.try(:price) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UsersLocation</title>
  <%= csrf_meta_tags %>
  <meta charset="utf-8" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div id="container">
    <% if user_signed_in? %>
    <li>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
    </li>
    <% else %>
    <li>
      <%= link_to('Login', new_user_session_path)  %>  
    </li>
    <li>
      <%= link_to('Register', new_user_registration_path)  %>
    </li>
    <% end %>
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/pdf/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.try(:name) %>
</p>

<p>
  <strong>Released on:</strong>
  <%= @product.try(:released_on) %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.try(:price) %>
</p>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
<% if product.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

  <ul>
    <% product.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name, id: :product_name %>
</div>

<div class="field">
  <%= form.label :released_on %>
  <%= form.date_select :released_on, id: :product_released_on %>
</div>

<div class="field">
  <%= form.label :price %>
  <%= form.text_field :price, id: :product_price %>
</div>
<%= form.check_box :special, {}, "true", "false" %>This Article u are buy 
<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/products/_product.html.erb
<tr>
  <td><%= product.name %></td>
  <td><%= product.released_on.strftime("%B %e, %Y") %></td>
  <td><%= number_to_currency(product.price) %></td>
  <td><%= link_to 'Show', product %></td>
  <td><%= link_to 'Edit', edit_product_path(product) %></td>
  <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.csv.erb
<%- headers = ['Name', 'released_on', 'price'] -%>
<%= CSV.generate_line headers %>
<%- @products.each do |product| -%>
<%= CSV.generate_line([product.name, product.released_on, product.price]) -%>
<%- end -%>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to "CSV", products_path(format: "csv") %> <br>
<%= link_to "Excel", products_path(format: "xls") %><br>


<p>
  Download PDF:
  <%= link_to 'PDF document',  pdf_path(format: "pdf"), target: '_blank'  %>
</p>

<h1>Products</h1>
<table id="products">
  <tr>
    <th>Product Name</th>
    <th>Release Date</th>
    <th>Price</th>
  </tr>
  <%= render @products %>
</table>
<%= link_to 'New Product', new_product_path %>

app/views/products/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Release Date</Data></Cell>
        <Cell><Data ss:Type="String">Price</Data></Cell>
      </Row>
    <% @products.each do |product| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= product.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.released_on %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.price %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
  <!-- Download: -->
  <%= link_to "CSV", products_path(format: "csv") %> 
  <%= link_to "Excel", products_path(format: "xls") %>
  
<%if @product.special%>
<p>
  Download PDF:
  <%= link_to 'PDF document', download_path(format: "pdf"), target: '_blank'  %>
</p>
<%else%>
<p>
  Download PDF:
  <%= link_to 'PDF document',  pdf_path(format: "pdf"), target: '_blank'  %>
</p>
<%end%>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Released on:</strong>
  <%= @product.released_on %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>